# Generated by Django 6.1.1 on 2026-09-08 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("🛒", "Продукты"),
                            ("🍽️", "Кафе и рестораны"),
                            ("🚗", "Транспорт"),
                            ("🚌", "Автобус"),
                            ("🚇", "Метро"),
                            ("🏠", "Жильё"),
                            ("💡", "Коммунальные услуги"),
                            ("📱", "Связь"),
                            ("🎮", "Развлечения"),
                            ("🎬", "Кино"),
                            ("🎵", "Музыка"),
                            ("🏥", "Здоровье"),
                            ("💊", "Лекарства"),
                            ("✈️", "Путешествия"),
                            ("🏝️", "Отдых"),
                            ("👕", "Одежда"),
                            ("👗", "Обувь"),
                            ("📚", "Образование"),
                            ("🎓", "Учёба"),
                            ("🎁", "Подарки"),
                            ("💼", "Зарплата"),
                            ("💻", "Фриланс"),
                            ("📈", "Инвестиции"),
                            ("💰", "Кэшбэк"),
                            ("🏆", "Бонус"),
                            ("🏘️", "Аренда"),
                            ("📊", "Дивиденды"),
                            ("📁", "Другое"),
                        ],
                        default="📁",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Доход"), ("expense", "Расход")],
                        default="expense",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(verbose_name="Дата")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="expenses.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
